"use client";

import React, { useRef } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import {
  FileText,
  Printer,
  Download,
  CheckCircle2,
  AlertTriangle,
  Clock,
  Pill,
  ShieldAlert,
  Sparkles,
  User,
  Calendar,
  Activity,
  HeartPulse,
} from "lucide-react";

export type MedicalReportData = {
  sessionId?: string;
  agent?: string;
  user?: string;
  timestamp?: string;
  chiefComplaint?: string;
  summary?: string;
  symptoms?: string[];
  duration?: string;
  severity?: string;
  medicationsMentioned?: string[];
  recommendations?: string[];
};

type MedicalReportDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  report: MedicalReportData | null;
  doctorImage?: string;
  doctorSpecialist?: string;
};

export default function MedicalReportDialog({
  open,
  onOpenChange,
  report,
  doctorSpecialist,
}: MedicalReportDialogProps) {
  const printRef = useRef<HTMLDivElement>(null);

  if (!report) return null;

  const severityLower = (report.severity || "").toLowerCase();
  let severityBadgeClass =
    "bg-slate-100 text-slate-700 border-slate-300";
  if (severityLower.includes("mild")) {
    severityBadgeClass =
      "bg-emerald-50 text-emerald-800 border-emerald-300 ring-1 ring-emerald-400/30";
  } else if (severityLower.includes("moderate")) {
    severityBadgeClass =
      "bg-amber-50 text-amber-800 border-amber-300 ring-1 ring-amber-400/30";
  } else if (severityLower.includes("severe")) {
    severityBadgeClass =
      "bg-rose-50 text-rose-800 border-rose-300 ring-1 ring-rose-400/30";
  }

  const handlePrint = () => {
    if (typeof window === "undefined") return;
    window.print();
  };

  const handleDownload = () => {
    const textContent = `
=========================================
      MEDI-VOICE AI CLINICAL REPORT      
=========================================
Session ID: ${report.sessionId || "N/A"}
Date & Time: ${report.timestamp ? new Date(report.timestamp).toLocaleString() : new Date().toLocaleString()}
Medical Specialist: ${report.agent || doctorSpecialist || "AI Doctor"}
Patient: ${report.user || "Patient"}

1. CHIEF COMPLAINT:
${report.chiefComplaint || "Not specified"}

2. CLINICAL SUMMARY:
${report.summary || "No summary provided"}

3. REPORTED SYMPTOMS:
${(report.symptoms || []).map((s) => `• ${s}`).join("\n") || "None noted"}

4. DURATION & SEVERITY:
- Duration: ${report.duration || "Not specified"}
- Severity: ${report.severity || "Not assessed"}

5. MEDICATIONS MENTIONED:
${(report.medicationsMentioned || []).map((m) => `• ${m}`).join("\n") || "None"}

6. RECOMMENDATIONS & ACTION PLAN:
${(report.recommendations || []).map((r, i) => `${i + 1}. ${r}`).join("\n") || "Consult a healthcare provider"}

-----------------------------------------
DISCLAIMER: This automated clinical summary was generated by Medi-Voice AI for informational purposes and does not replace in-person medical diagnosis or prescription. Always consult a licensed healthcare professional.
=========================================
    `.trim();

    const blob = new Blob([textContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `medical-report-${(report.sessionId || "session").slice(0, 8)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-3xl md:max-w-4xl lg:max-w-4xl w-[94vw] max-h-[88vh] flex flex-col p-0 overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-2xl transition-all duration-200">
        {/* Modal Header */}
        <DialogHeader className="px-6 sm:px-8 pt-6 pb-4 border-b border-gray-100 bg-gradient-to-r from-blue-50/60 via-white to-slate-50/40">
          <div className="flex items-center justify-between pr-8">
            <div className="flex items-center gap-3.5">
              <div className="w-11 h-11 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center text-primary shadow-xs">
                <FileText className="w-6 h-6 text-primary" />
              </div>
              <div>
                <DialogTitle className="text-xl sm:text-2xl font-extrabold text-gray-900 tracking-tight flex items-center gap-2">
                  Clinical Consultation Report
                  <Sparkles className="w-4 h-4 text-amber-500 fill-amber-500" />
                </DialogTitle>
                <DialogDescription className="text-xs sm:text-sm text-gray-500 mt-0.5">
                  Automated medical summary generated from your AI consultation.
                </DialogDescription>
              </div>
            </div>
          </div>
        </DialogHeader>

        {/* Scrollable Report Body */}
        <div
          ref={printRef}
          className="flex-1 overflow-y-auto px-6 sm:px-8 py-6 space-y-6 text-gray-800"
        >
          {/* Top Metadata Grid: 4 spacious cards */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
            <div className="p-3.5 rounded-xl bg-slate-50/80 border border-slate-200/80 flex items-center gap-3 shadow-2xs">
              <div className="w-9 h-9 rounded-lg bg-blue-100/70 text-blue-700 flex items-center justify-center flex-shrink-0">
                <User className="w-4 h-4" />
              </div>
              <div className="min-w-0">
                <span className="text-[11px] text-slate-500 font-medium block uppercase tracking-wide">
                  Patient
                </span>
                <span className="font-bold text-slate-800 text-sm truncate block">
                  {report.user || "Patient"}
                </span>
              </div>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50/80 border border-slate-200/80 flex items-center gap-3 shadow-2xs">
              <div className="w-9 h-9 rounded-lg bg-indigo-100/70 text-indigo-700 flex items-center justify-center flex-shrink-0">
                <Calendar className="w-4 h-4" />
              </div>
              <div className="min-w-0">
                <span className="text-[11px] text-slate-500 font-medium block uppercase tracking-wide">
                  Date
                </span>
                <span className="font-bold text-slate-800 text-sm block">
                  {report.timestamp
                    ? new Date(report.timestamp).toLocaleDateString()
                    : new Date().toLocaleDateString()}
                </span>
              </div>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50/80 border border-slate-200/80 flex items-center gap-3 shadow-2xs">
              <div className="w-9 h-9 rounded-lg bg-rose-100/70 text-rose-700 flex items-center justify-center flex-shrink-0">
                <HeartPulse className="w-4 h-4" />
              </div>
              <div className="min-w-0">
                <span className="text-[11px] text-slate-500 font-medium block uppercase tracking-wide">
                  Specialist
                </span>
                <span className="font-bold text-slate-800 text-sm truncate block">
                  {report.agent || doctorSpecialist || "AI Specialist"}
                </span>
              </div>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50/80 border border-slate-200/80 flex items-center gap-3 shadow-2xs">
              <div className="w-9 h-9 rounded-lg bg-amber-100/70 text-amber-700 flex items-center justify-center flex-shrink-0">
                <Activity className="w-4 h-4" />
              </div>
              <div className="min-w-0">
                <span className="text-[11px] text-slate-500 font-medium block uppercase tracking-wide">
                  Severity
                </span>
                <span
                  className={`inline-block px-2.5 py-0.5 rounded-md text-xs font-bold border capitalize ${severityBadgeClass}`}
                >
                  {report.severity || "Not assessed"}
                </span>
              </div>
            </div>
          </div>

          {/* Chief Complaint Banner */}
          <div className="p-5 rounded-2xl bg-amber-50/80 border border-amber-200/80 shadow-2xs">
            <div className="flex items-center gap-2 text-amber-900 font-bold text-xs uppercase tracking-wider mb-2">
              <AlertTriangle className="w-4 h-4 text-amber-600 flex-shrink-0" />
              Chief Health Concern
            </div>
            <p className="text-base font-semibold text-amber-950 leading-relaxed">
              &ldquo;{report.chiefComplaint || "None specified"}&rdquo;
            </p>
          </div>

          {/* Clinical Summary Narrative */}
          <div className="p-5 rounded-2xl bg-slate-50/90 border border-slate-200/80 shadow-2xs">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2.5 flex items-center gap-2">
              <FileText className="w-4 h-4 text-primary" />
              Clinical Summary
            </h4>
            <p className="text-sm leading-relaxed text-slate-700 font-normal">
              {report.summary || "No summary recorded for this session."}
            </p>
          </div>

          {/* 2-Column Grid: Symptoms & Clinical Context */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Symptoms Identified */}
            <div className="p-5 rounded-2xl bg-slate-50/90 border border-slate-200/80 shadow-2xs flex flex-col justify-between">
              <div>
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-3 flex items-center gap-2">
                  <Activity className="w-4 h-4 text-rose-500" />
                  Symptoms Identified
                </h4>
                {report.symptoms && report.symptoms.length > 0 ? (
                  <div className="flex flex-wrap gap-2">
                    {report.symptoms.map((symptom, i) => (
                      <span
                        key={i}
                        className="px-3 py-1 rounded-full text-xs font-semibold bg-rose-50 text-rose-800 border border-rose-200 shadow-2xs"
                      >
                        {symptom}
                      </span>
                    ))}
                  </div>
                ) : (
                  <p className="text-xs text-slate-400 italic">
                    No specific symptoms cataloged.
                  </p>
                )}
              </div>
            </div>

            {/* Duration & Medications */}
            <div className="p-5 rounded-2xl bg-slate-50/90 border border-slate-200/80 shadow-2xs space-y-4">
              <div>
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5 flex items-center gap-2">
                  <Clock className="w-4 h-4 text-blue-500" />
                  Symptom Duration
                </h4>
                <p className="text-xs sm:text-sm font-semibold text-slate-800">
                  {report.duration || "Not specified"}
                </p>
              </div>

              <div className="pt-2 border-t border-slate-200/60">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5 flex items-center gap-2">
                  <Pill className="w-4 h-4 text-indigo-500" />
                  Medications Mentioned
                </h4>
                {report.medicationsMentioned &&
                report.medicationsMentioned.length > 0 ? (
                  <div className="flex flex-wrap gap-1.5">
                    {report.medicationsMentioned.map((med, i) => (
                      <span
                        key={i}
                        className="px-2.5 py-1 rounded-md text-xs font-medium bg-indigo-50 text-indigo-800 border border-indigo-200"
                      >
                        {med}
                      </span>
                    ))}
                  </div>
                ) : (
                  <p className="text-xs text-slate-400 italic">
                    None mentioned
                  </p>
                )}
              </div>
            </div>
          </div>

          {/* Recommendations & Action Plan */}
          <div className="p-5 rounded-2xl bg-slate-50/90 border border-slate-200/80 shadow-2xs">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-3 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
              Doctor&apos;s Recommendations & Action Plan
            </h4>
            <div className="space-y-2.5">
              {report.recommendations && report.recommendations.length > 0 ? (
                report.recommendations.map((rec, i) => (
                  <div
                    key={i}
                    className="flex items-start gap-3 p-3.5 rounded-xl bg-emerald-50/70 border border-emerald-200/90 text-xs sm:text-sm text-emerald-950"
                  >
                    <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0 mt-0.5" />
                    <span className="font-medium leading-relaxed">{rec}</span>
                  </div>
                ))
              ) : (
                <div className="p-3.5 rounded-xl bg-white border border-slate-200 text-xs text-slate-500">
                  Follow up with your primary physician for customized advice.
                </div>
              )}
            </div>
          </div>

          {/* Medical Disclaimer Warning */}
          <div className="p-4 rounded-xl bg-amber-50/70 border border-amber-200/70 text-xs text-amber-900/90 flex items-start gap-2.5">
            <ShieldAlert className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
            <p className="leading-relaxed">
              <strong className="font-semibold text-amber-950">
                Medical Disclaimer:
              </strong>{" "}
              This summary is generated by artificial intelligence for informational and record-keeping purposes only. It is not an official medical diagnosis, prescription, or treatment plan. If you are experiencing severe symptoms or an emergency, call your local emergency services (e.g. 911 / 112) immediately.
            </p>
          </div>
        </div>

        {/* Modal Footer Actions */}
        <div className="w-full px-6 sm:px-8 py-4 bg-slate-50 border-t border-gray-200/90 flex flex-row items-center justify-between gap-4 rounded-b-2xl">
          <div className="text-xs text-slate-500 font-mono flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-emerald-500 flex-shrink-0" />
            <span className="hidden sm:inline">Session ID:</span>
            <span className="font-semibold text-slate-700">
              {report.sessionId?.slice(0, 16)}...
            </span>
          </div>
          <div className="flex items-center gap-3 flex-shrink-0">
            <Button
              variant="outline"
              size="sm"
              onClick={handlePrint}
              className="border-gray-300 text-gray-700 hover:bg-gray-100 text-xs gap-1.5 h-9 px-3.5 shadow-2xs"
            >
              <Printer className="w-4 h-4" />
              Print Report
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownload}
              className="border-gray-300 text-gray-700 hover:bg-gray-100 text-xs gap-1.5 h-9 px-3.5 shadow-2xs"
            >
              <Download className="w-4 h-4" />
              Download .txt
            </Button>
            <Button
              size="sm"
              onClick={() => onOpenChange(false)}
              className="bg-primary hover:bg-primary/90 text-white font-semibold text-xs h-9 px-5 shadow-xs"
            >
              Close
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
